# Pour exécution LOCALE avec Postgres dans Docker (docker-compose.db-only.yml)
# Lancer : java -jar ... --spring.profiles.active=docker,docker-local
spring.datasource.url=jdbc:postgresql://localhost:5433/enrollments_db
course.service.url=http://localhost:8083
