apiVersion: v1
kind: Service
metadata:
  name: enrollment-service
  labels:
    app: enrollment-service
spec:
  selector:
    app: enrollment-service
  ports:
    - name: http
      port: 8084
      targetPort: http
  type: ClusterIP

