- name: Checkout
  uses: actions/checkout@v4

- name: Setup Java
  uses: actions/setup-java@v4
  with:
    distribution: 'temurin'
    java-version: '17'

- name: Give execute permission to mvnw
  run: chmod +x Enrollment-service/mvnw

- name: Build & Test
  run: |
    cd Enrollment-service
    ./mvnw clean verify
