name: CI - Course Service

on:
  push:
    branches: [ "main" ]
    paths:
      - "course-service/**"
      - ".github/workflows/course-ci.yml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "course-service/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Give execute permission to mvnw
        run: chmod +x course-service/mvnw

      - name: Build and test
        run: |
          cd course-service
          ./mvnw clean verify
